import { ThemeProvider } from "@/contexts/ThemeContext";
import { poppins } from "@/components/ui/fonts/fonts";
import type { Metadata } from "next";
import Providers from "./Providers";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "CashWell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en" className="h-full">
        <body className={`${poppins.className} antialiased min-h-dvh bg-background`}>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </body>
      </html>
    </ThemeProvider>
  );
}
